# Generated by Django 5.0.3 on 2024-04-03 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product_brand', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand')),
            ],
        ),
    ]
