# Generated by Django 5.0.3 on 2024-04-03 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.brand'),
        ),
    ]
