# Generated by Django 5.0.3 on 2024-04-07 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stock_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='tag',
            field=models.ManyToManyField(related_name='brand_tags', to='inventory.tag'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time_created')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time_updated')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is_published')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category')),
            ],
        ),
    ]
