# Generated by Django 5.0.3 on 2024-04-07 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_brand_tag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_brand', to='inventory.brand'),
        ),
    ]
